apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
spec:
  replicas: 1
  selector:
    # matchLabels:
    #   app: second-app
    #   tier: backend
    matchExpressions:
      - {key: app, operator: In, values: [second-app]}
      - {key: tier, operator: In, values: [backend]}
  template:
    metadata: 
      labels:
        app: second-app
        tier: backend
    spec: 
      containers:
        - name: second-node
          image: mayankcse1/kub-first-app:latest
        # - name: ...
        #   image: ...
